services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chronos
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      # oltp receiver
      - 4318:4318
      #  query api + ui
      - 16686:16686
  

volumes:
  postgres_data:
  prometheus_data:
