// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE
  jobs
SET
  status = 'IN_PROGRESS',
  visible_after = $1,
  updated_at = NOW(),
  claimed_by = $2
WHERE
  id =(
    SELECT
      id
    FROM
      jobs
    WHERE
      status = 'PENDING'
      OR (status = 'RETRYING'
        AND next_retry_at <= NOW())
      OR (status = 'IN_PROGRESS'
        AND visible_after IS NOT NULL
        AND visible_after <= NOW())
    ORDER BY
      created_at ASC
    LIMIT 1
    FOR UPDATE
      SKIP LOCKED)
RETURNING
  id, type, payload, status, retry_count, max_retries, idempotency_key, next_retry_at, created_at, updated_at, visible_after, claimed_by, dlq_reason, failed_at
`

type ClaimJobParams struct {
	VisibleAfter pgtype.Timestamptz
	ClaimedBy    pgtype.Text
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.VisibleAfter, arg.ClaimedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.IdempotencyKey,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleAfter,
		&i.ClaimedBy,
		&i.DlqReason,
		&i.FailedAt,
	)
	return i, err
}

const countDeadLetterJobs = `-- name: CountDeadLetterJobs :one
SELECT
  COUNT(*)
FROM
  jobs
WHERE
  status = 'FAILED'
`

func (q *Queries) CountDeadLetterJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeadLetterJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs(id, type, payload, status, max_retries, idempotency_key, created_at, updated_at)
  VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING
  id, type, payload, status, retry_count, max_retries, idempotency_key, next_retry_at, created_at, updated_at, visible_after, claimed_by, dlq_reason, failed_at
`

type CreateJobParams struct {
	ID             string
	Type           string
	Payload        []byte
	Status         string
	MaxRetries     int32
	IdempotencyKey pgtype.Text
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.Status,
		arg.MaxRetries,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.IdempotencyKey,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleAfter,
		&i.ClaimedBy,
		&i.DlqReason,
		&i.FailedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT
  id, type, payload, status, retry_count, max_retries, idempotency_key, next_retry_at, created_at, updated_at, visible_after, claimed_by, dlq_reason, failed_at
FROM
  jobs
WHERE
  id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.IdempotencyKey,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleAfter,
		&i.ClaimedBy,
		&i.DlqReason,
		&i.FailedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT
  id, type, payload, status, retry_count, max_retries, idempotency_key, next_retry_at, created_at, updated_at, visible_after, claimed_by, dlq_reason, failed_at
FROM
  jobs
WHERE
  idempotency_key = $1
`

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, idempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.IdempotencyKey,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleAfter,
		&i.ClaimedBy,
		&i.DlqReason,
		&i.FailedAt,
	)
	return i, err
}

const listDeadLetterJobs = `-- name: ListDeadLetterJobs :many
SELECT
  id, type, payload, status, retry_count, max_retries, idempotency_key, next_retry_at, created_at, updated_at, visible_after, claimed_by, dlq_reason, failed_at
FROM
  jobs
WHERE
  status = 'FAILED'
ORDER BY
  failed_at DESC
LIMIT $1 OFFSET $2
`

type ListDeadLetterJobsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDeadLetterJobs(ctx context.Context, arg ListDeadLetterJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listDeadLetterJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.IdempotencyKey,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VisibleAfter,
			&i.ClaimedBy,
			&i.DlqReason,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT
  id, type, payload, status, retry_count, max_retries, idempotency_key, next_retry_at, created_at, updated_at, visible_after, claimed_by, dlq_reason, failed_at
FROM
  jobs
WHERE
  status = 'PENDING'
`

func (q *Queries) ListPendingJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listPendingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.IdempotencyKey,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VisibleAfter,
			&i.ClaimedBy,
			&i.DlqReason,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE
  jobs
SET
  status = $2,
  retry_count = $3,
  next_retry_at = $4,
  dlq_reason = $5,
  failed_at = CASE WHEN $2 = 'FAILED' THEN
    NOW()
  ELSE
    failed_at
  END,
  updated_at = NOW()
WHERE
  id = $1
`

type UpdateJobStatusParams struct {
	ID          string
	Status      string
	RetryCount  int32
	NextRetryAt pgtype.Timestamptz
	DlqReason   pgtype.Text
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.RetryCount,
		arg.NextRetryAt,
		arg.DlqReason,
	)
	return err
}

const updateJobVisibility = `-- name: UpdateJobVisibility :exec
UPDATE
  jobs
SET
  visible_after = $2,
  updated_at = NOW()
WHERE
  id = $1
`

type UpdateJobVisibilityParams struct {
	ID           string
	VisibleAfter pgtype.Timestamptz
}

func (q *Queries) UpdateJobVisibility(ctx context.Context, arg UpdateJobVisibilityParams) error {
	_, err := q.db.Exec(ctx, updateJobVisibility, arg.ID, arg.VisibleAfter)
	return err
}
