// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID             string
	Type           string
	Payload        []byte
	Status         string
	RetryCount     int32
	MaxRetries     int32
	IdempotencyKey pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
